# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_auto_20170202_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
