# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0010_property_is_editable'),
        ('attachments', '0010_property_allowed_file_types'),
    ]

    operations = [
    ]
