# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0011_session_allowed_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='known_file_types',
            field=models.TextField(blank=True, help_text='An allowed_file_types override in the form of whitespace separated string in the form of file types:file extension'),
        ),
    ]
