# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-17 20:18
from __future__ import unicode_literals

import attachments.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0011_session_allowed_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='known_file_types',
            field=attachments.utils.JSONField(help_text='An allowed_file_types override in the form of a dictionary with keys being the extension and values the file_type', null=True),
        ),
    ]
