# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0012_auto_20180906_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='choices',
            field=models.TextField(blank=True, help_text='Lookup choices for a ChoiceField, one per line.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='data_type',
            field=models.CharField(choices=[('string', 'Text'), ('text', 'Large Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('email', 'Email Address'), ('choice', 'Choice'), ('model', 'Model')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='model',
            field=models.CharField(blank=True, help_text='The path to the lookup model for a ModelChoiceField.', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(help_text='Must be alphanumeric, with no spaces.', unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='template',
            field=models.CharField(default='attachments/list.html', max_length=200),
        ),
    ]
