# Generated by Django 3.2.13 on 2022-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0013_auto_20191107_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='chunk_index_to_resume_on',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_size',
            field=models.BigIntegerField(),
        ),
    ]
