# Generated by Django 3.2.20 on 2023-09-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0014_auto_20220615_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='unpack_zip_files',
            field=models.BooleanField(default=False, help_text='If True, .zip file members will be attached, instead of the .zip file itself.'),
        ),
    ]
