# Generated by Django 3.2.18 on 2023-04-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0014_auto_20220615_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='template',
            field=models.CharField(default='attachments/bootstrap/list.html', max_length=200),
        ),
    ]
