# Generated by Django 4.2.28 on 2026-02-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0016_alter_attachment_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
