name: CI

on:
  - push
  - pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Upgrade pip setuptools wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install Checkers
        run: pip install jake ruff djlint

      - name: jake
        run: jake ddt
        continue-on-error: true

      - name: ruff
        run: ruff check .
        continue-on-error: true

      - name: djlint-formatting
        run: djlint --check .
        continue-on-error: true

      - name: djlint-linting
        run: djlint --lint .
        continue-on-error: true
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: django-dynamic-attachments
          POSTGRES_PASSWORD: django-dynamic-attachments-secret
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Upgrade pip setuptools wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install requirements
        run: pip install "Django>=3.2.23,<=4.2.9" "coverage==3.7.1" "ims-bootstrap<6"
          "pyclamd==0.4.0" "python-magic>=0.4.15"

      - name: Run Tests (PostgreSQL)
        run: python manage.py test
        continue-on-error: true

      - name: Run Tests (SQLite)
        run: TEST_ENGINE=sqlite python manage.py test
        continue-on-error: true
