name: CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Checkers
      run: pip install jake black isort flake8 djlint
    - name: jake
      run: jake ddt
    - name: black
      run: black --check .
    - name: isort
      run: isort --check .
    - name: flake8
      run: flake8
    - name: djlint-formatting
      run: djlint --check .
    - name: djlint-linting
      run: djlint --lint .

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: django-dynamic-attachments
          POSTGRES_PASSWORD: django-dynamic-attachments-secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements
      run: pip install "Django>=3.2.23,<=4.2.9" coverage pyclamd python-magic
    - name: Run Tests (PostgreSQL)
      run: python manage.py test
    - name: Run Tests (SQLite)
      run: TEST_ENGINE=sqlite python manage.py test
