permissions: read-all

name: CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.11

      - name: Install Checkers
        run: pip install ruff djlint

      - name: ruff
        run: ruff check .
        continue-on-error: true

      - name: djlint-formatting
        run: djlint --check .
        continue-on-error: true

      - name: djlint-linting
        run: djlint --lint .
        continue-on-error: true
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine@sha256:d8c54117c24479e0a05b31f7743d8704cfec5ba2604618da44df7d6dfa1cc79e
        env:
          POSTGRES_DB: django-dynamic-attachments
          POSTGRES_PASSWORD: django-dynamic-attachments-secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.11

      - name: Install requirements
        run: pip install "django>=5.2.14,<6" "coverage==7.14.0" "ims-bootstrap>=5.3.2,<6"
          "python-magic>=0.4.27"

      - name: Run Tests (PostgreSQL)
        run: python manage.py test
        continue-on-error: true

      - name: Run Tests (SQLite)
        run: TEST_ENGINE=sqlite python manage.py test
        continue-on-error: true
